Demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('movie/', include('movie.urls', namespace='movie')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
import django.contrib.auth.views as auth_views

from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('register/', views.register, name='register'),
    path('register_done/', views.register, name='register_done'),
    path('edit/', views.edit, name='edit'),
    path('profile/<int:profile_id>/', views.profile, name='profile'),
]

homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

movie/urls.py
from django.contrib import admin
from . import views
from django.urls import path

app_name = 'movie'

urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('search/', views.movie_search, name='movie_search'),
    path('<int:id>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/review/', views.movie_review, name='movie_review'),
    path('<int:movie_id>/review/edit', views.edit_review, name='movie_edit_review'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns:accounts="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}IMDb{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
</head>
<body>
<div class="nav">
    <div class="link"><a href="{% url 'homepage:homepage' %}">Homepage</a></div>
    <div class="link"><a href="{% url 'movie:movie_list' %}">Movies</a></div>
    <form method="get" action="{% url 'movie:movie_search' %}" accept-charset="UTF-8">
        {{ search_form.as_p }}
        <!-- <input type="text" placeholder="Search..."/>
        <button type="submit" value="Submit">
            <i class="fa fa-search"></i>
        </button> -->
    </form>
    {% if request.user.is_authenticated %}
    <div class="link"><a href="{% url 'accounts:profile' profile_id=request.user.profile.id %}">Profile</a></div>
    <div class="link"><a href="{% url 'accounts:logout' %}">Log-out</a></div>
    {% else %}
    <div class="link"><a href="{% url 'accounts:login' %}">Log-in</a></div>
    {% endif %}
    <div class="link" id="about"><a href="">About</a></div>
</div>
{% block content %}
{% endblock %}
</body>
</html>